# Generated by Django 4.2.16 on 2024-09-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(default=0),
        ),
    ]
