# Generated by Django 4.2.16 on 2024-09-17 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_product_productitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created At"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(verbose_name="Stock"),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="qr_code",
            field=models.ImageField(
                upload_to="./media/qr_codes/", verbose_name="QR Code"
            ),
        ),
    ]
