# Generated by Django 4.2.16 on 2024-09-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0005_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="./media/product_images/",
                verbose_name="Product Image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(verbose_name="Stock"),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="analysis.product",
                verbose_name="Product",
            ),
        ),
    ]
