# Generated by Django 4.2.16 on 2024-09-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0006_alter_product_image_alter_product_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="analysis.product",
                verbose_name="Product",
            ),
        ),
    ]
