# Generated by Django 4.2.16 on 2024-09-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0007_alter_productitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Stock"
            ),
        ),
    ]
